version: '3.8'

services:
  frontend_leema:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-leema
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - leema-network

networks:
  leema-network:
    driver: bridge
