version: '3.8'

services:
  frontend_leema:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: frontend-leema
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - leema-network
    volumes:
      # Mount source directories for hot reload
      - ../public:/usr/share/nginx/html/public
      - ../shop:/usr/share/nginx/html/shop
      - ../user:/usr/share/nginx/html/user
      - ../admin:/usr/share/nginx/html/admin
      - ../assets:/usr/share/nginx/html/assets
      # Mount favicon files
      - ../favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ../favicon-16x16.png:/usr/share/nginx/html/favicon-16x16.png:ro
      - ../favicon-32x32.png:/usr/share/nginx/html/favicon-32x32.png:ro
      - ../apple-touch-icon.png:/usr/share/nginx/html/apple-touch-icon.png:ro
      - ../android-chrome-192x192.png:/usr/share/nginx/html/android-chrome-192x192.png:ro
      - ../android-chrome-512x512.png:/usr/share/nginx/html/android-chrome-512x512.png:ro
      - ../logo.png:/usr/share/nginx/html/logo.png:ro
      # Mount nginx config for hot reload
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  leema-network:
    driver: bridge
